# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:WqNTDUTTw4I6a1k=,iv:F9g3fijU4yNUhXgBXxvPHgl2+tewoaXy17mxEivKZSI=,tag:E6muo8u1aDenDLTrXUycIw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:C4hpAVe14OQbBNoA1DUr6g5nPenN6Squ8WQ=,iv:B6rxIrmWV1M83Z5DulsCET3GIR8wNaonAYEb+F10kAg=,tag:UdxMkXOHqGwwCZdo71wMzQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nca9p3pvg0sq52wgqmfld3j7qmp9wfpnnntfzh9tlchh4du0ja7snx8r4m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q25qbVFDci94ZEJCaHZz
        NG4ySVJIY0N5cHMrRzBWTW5sT2I2WHVoMGhjCjJzNVpLVG4zSlVRQlR3cmF2QzNV
        akZpR0x1b1NjR1FKYzIwYjhyM3YvWHMKLS0tIHJyTmZIV0h1RFFMNkp3U2dVZms1
        Z2JNV1NtSGNpVklobDBqSHk3d1pQVUEK2RbZJPVhT8gqN0iEvuC3niO7THb0jTcR
        gTrncPrL7Xqc0djnYzTgfDDyOgEzAIzDIKO7luI5KM3Zf5EGL7qwgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T13:00:22Z"
  mac: ENC[AES256_GCM,data:GI7ILg+5Gx2ZwK29oyOcmU1bawIQlnSNGjF3WqMwnSPy6o3G6wev8rMt15kaccoLhH1tJowtxoJmYZHBV613g1ON5JhkzdxtJvu7z2bxCyQ9QxeHIdsIN+Vqy/QaKMYpW8l4L+dHlMD8rlJA7/rz+5TQD7HHffkqLqGI5Dwtia8=,iv:7uSyCgEtNNS/nNTsllHO4F2cSx3TN2BwollLsC8ansc=,tag:xgoH1DsVzX+Bn+9vfMxP/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
