apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 6m
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  chart:
    spec:
      chart: authentik
      version: "2024.12.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system

  valuesFrom:
  - kind: Secret
    name: authentik-secrets
    valuesKey: values.yaml
  values:

    # authentik: in secrets.sops.yaml

    postgresql:
      enabled: false

    # redis: in secrets.sops.yaml

    server:
      autoscaling:
        enabled: true
        minReplicas: 1
      ingress:
        enabled: true
        ingressClassName: external
        pathType: Prefix
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: authentik.png
          gethomepage.dev/name: Authentik
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/app: authentik
          gethomepage.dev/description: OIDC User Management
          gethomepage.dev/widget.type: authentik
        hosts:
          - auth.${SECRET_DOMAIN}
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.${SECRET_DOMAIN}

    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
