apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-pvc
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Gi
