# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2Mc1ivydWY6vgataW9/FzdqurhQhjQvAazVNZ+N/+AaQGHnIQ4QacA==,iv:HR5LPAE+RQgKdYOrcdPXnvs8AN1zpxrGnVb41sKj2Ok=,tag:SDNdvsk5DjRalozz6KgiOQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nca9p3pvg0sq52wgqmfld3j7qmp9wfpnnntfzh9tlchh4du0ja7snx8r4m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ1ZpOWpwSEk3WDF3ZUw0
        REtOOXpQNUo4M1psUm9ERTRaY09hMzlidG5vCkI1ZmFYakRSYktaSnB6dmIrQmEr
        cldWaTgxSTdtODRDLzFkMVVmNkh4SkUKLS0tIHNvMitQSkFXc2dMOGh2M1BwZ3Bh
        SzAzZTJZSVpEdC9nbE5KN2JtM2FKeTgKtrpKEQWavC9JQsycVm2w9/s8/KoMOBCx
        S8PlvmpiOi2cpW85TFHYdPJLNTOcbFVQcNOxLjuNLyw9BlPDwmJ1fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T22:39:00Z"
  mac: ENC[AES256_GCM,data:oPeawkCTW4xkMbgNb1yvwP4CryPhXD/w0YqYBybSWz7RcephoUkohvHjED4yKO8HIvb4vyFmmPtMgbgFnCGpSuZCLx1GZWi/M5QOc9PFhWpLoS5kaZBGKnQcEUTrF27AkgPdG9ObvwjAx20KGCCSsB3MWWPx4VTGLXny8UwrhX8=,iv:v4tluK4mrXt1yWcDlHx3GTN+uxlvcTY5C8P6Nj9Z+EI=,tag:cubCDyc7ERusNCOeML2xGQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
