# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8JhPQkcvDQg/e+SwBE657zsRlcBXDLFAv/FBIvHetiVWfgWnezMM7Q==,iv:Xxu/UDPYlf8OvdwtRAJo8gAn2xYJplxdGT1KA50ozy4=,tag:Eb/ZHlPvXUBxjBxAvpZ6rw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nca9p3pvg0sq52wgqmfld3j7qmp9wfpnnntfzh9tlchh4du0ja7snx8r4m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbzJjUGpQbXE0YVc3Vmh1
        M0lnTHRRbGoxalZDWVE0OGU4QWZRMXpRTFhzCmhzdnZhVWFSdXBET3U1R0lpSGtS
        UDZ2WkprYWk1SEt0b1FEdWg3enBsb3MKLS0tIDZ6SitsUXpuTGhxUTlZNzZXV1Mx
        OS9XOWErUEluNVR3YTRzM2g5VERJZk0KhyX7EsYtFGCtvRdoLqKGrrPuF1CsFhDy
        ER8oVq8J8hOLQGopVzkK/1dqVXWn5rVRlssghtH5A7JbBg6XWjXsSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T13:00:22Z"
  mac: ENC[AES256_GCM,data:3V84yrUU4Ejmy9zHar37MBeY2tqtXB5HBasv+1lQ3gPeLH31U2Wz/vvm8lPIuHsvmqoD6i1GMYOtOqaeS7F3Z8h+KUZun8dhMAEY9zdo51B4iNaKNhssWR+9MTBbjH3i/0TT/Z+3TGCF9U6UjNf5a6kJ2prBGJU9LyX6uXJiJo4=,iv:+9E9YCMiYrgowetTmKefZS2xjJ4oqBKAF2DgTiJnnJM=,tag:+2JsTagAvBpwrHbQ/RFQtA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
