---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- homer.yaml
configMapGenerator:
  - name: homer-config
    files:
      - config.yml=./config/homer-config.yaml
generatorOptions:
  disableNameSuffixHash: true