apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkstack-pvc
  namespace: services
  labels:
    app.kubernetes.io/name: linkstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Gi
