# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:10R0C1If7BzGvb4yXbERomWYHBXIGLOS0UT5JoQnP8iJELGVjDLhwg==,iv:xum/eAC0cy1wrdsV/woRPFVk1b/9H7asscLmbC1IFaI=,tag:WG26ss+iu2euXF4AhmX8Zw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nca9p3pvg0sq52wgqmfld3j7qmp9wfpnnntfzh9tlchh4du0ja7snx8r4m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YkNFc3lodTUvclZtMnZt
        d3hKOUpiVVpuM2NZMHB1ZTJDTFBiRlljZFFJCjkvZXoxR2dQbHM0Z09sN3FkKy90
        Z2diMjM4ZDFONEFkUGNPS1VxS2VFQXMKLS0tIGszYmRXU0ZETGFwWGVJQVFNM3ho
        Yy80a1pxelo5cnN5TTJuK29jcjZWQ00KlsSdB07Tz2i2T447sfX9bU25I6lwxWB2
        HGlUTr6NZM3hfOzhEfk5WIO65XQzxZACuqb2sj4lmYUCm0buNcBP7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T13:00:22Z"
  mac: ENC[AES256_GCM,data:2SAG7mdX8SQJT423IvO3D2F8Nk4CmMGJl/1YX4w8wTmEreW4MfE1NHyiiKDXITeatLaEDzM0GdBmOn9F/LYp70diYzJxV3DGBWHtl3PrgAtKvdu0ge3j4IqLj20D75lzdr72ncm1sVfjy6OSpUvnxwie5pu1avCvhXmODpktuAE=,iv:BSSMwJ4S0043K2kVLGe49ABmwJdVFBxAA4iTKxqA/2Y=,tag:8aIWv4Qhk9u9NGMCCwwD/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
