# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:0as4kU1ey7o6uKBgxjP3TSoAwQ9WAuHQVqYW0zAf0gemLFQhwmQcuA==,iv:Ay0/3d/ZLJ2z46AnMLVGWTWLC7dpbSNxD8IVC/mT6C4=,tag:889O83UhQfsJ4p547x/q1Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nca9p3pvg0sq52wgqmfld3j7qmp9wfpnnntfzh9tlchh4du0ja7snx8r4m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSytSU25IRE93cjNFVmJr
        NFRtZ3M1c1c0ZjBkTFFVRXFVZ2tMZjUyTUhRCjE5eEZCbFdCalpUeS9kK1JmM3dY
        d21ucWQ5dGorTlV4YTNoeFIrZUUza2sKLS0tIGxoaDFDMVZOUi8vZmZ0ZjBDYjFT
        NitwcmpRYVhMV0hBR1lRaTFqQkZEWUEKcdoUYR/7T/dFzLlwJHpxEVkQHbQ+uDF8
        7n1DZaQVSIi1RYfJD2i0dU64VmjgNC6BEWgqw2b16+lpe0h3WcKVzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-28T21:28:05Z"
  mac: ENC[AES256_GCM,data:q9VgVjbBPPx7ZZ/gpQiazWuvmQfg6dmN8A9dAv/5tqXorg6e5z2fVJXs+zpzxFdzLZbGbQsMY9H+JmQGAHt9Zr7f454VmdGeHSTJGDtK900B5JEzDjTy9+IMZNTyZ96NXy11jnFYLDnRkWzLakwDOTmsauRy0K0RazTmT4Ezwyw=,iv:e5OSzgepXvXV7TPzoBOYUtJBkuw/OQUdaMPovwT0nlk=,tag:VhWT+3lNTDVJqHOE8GMRsQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
